[build-system]
requires = ["setuptools>=61.2", "jpy==2.1.0", "build==1.2.1"]
build-backend = "setuptools.build_meta"

[project]
name = "drools_jpy"
version = "0.4.1"
authors = [
  { name="Madhu Kanoor", email="author@example.com" },
]
description = "A Python package to directly call Drools Java classes from python"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
]
dependencies = [
"jpy==2.1.0",
]

[project.optional-dependencies]
local = [
   "flake8 == 7.1.1",
   "black == 24.10.0",
   "isort == 5.13.2",
   "pyyaml == 6.0.3"
]
tests = [
  # ---- Python 3.9 Specific Pinned Versions ----
    "coverage==7.4.4; python_version == '3.9'",
    "pytest==8.3.4; python_version == '3.9'",
    "pytest-asyncio==0.23.8; python_version == '3.9'",
    "pytest-cov==5.0.0; python_version == '3.9'",
    "tox==4.18.1; python_version == '3.9'",
    "tox-gh-actions==3.2.0; python_version == '3.9'",

    # ---- Fallbacks for Python 3.10 and Newer ----
    "coverage==7.15.2; python_version > '3.9'",
    "pytest==9.1.1; python_version > '3.9'",
    "pytest-asyncio==1.4.0; python_version > '3.9'",
    "pytest-cov==7.1.0; python_version > '3.9'",
    "tox==4.57.0; python_version > '3.9'",
    "tox-gh-actions==3.3.0; python_version > '3.9'"
]

dev = [
  "drools_jpy[local] == 0.4.1",
  "drools_jpy[tests] == 0.4.1"
]

[project.urls]
"Homepage" = "https://github.com/ansible/drools_jpy"
"Bug Tracker" = "https://github.com/ansible/drools_jpy/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
drools_jpy = ["*.jar"]



[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py39,py310,py311,py312
skip_missing_interpreters = true

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
passenv = JAVA_HOME
deps = pytest               # PYPI package providing pytest,
       jpy
       tox-wheel
       pyyaml
       pytest-asyncio
commands = pytest {posargs} # substitute with tox' positional arguments
wheels = true
"""

[tool.flake8]
max-line-length = 79
count = true
exclude = [
      '.tox',
      'docs',
      'venv',
      '.venv',
]


[tool.black]
line-length = 79

[tool.isort]
profile = 'black'
